import "./globals.css";
import Navbar from "@/components/Navbar/page";
import { Footer } from "@/components/Footer/page";

import { Montserrat } from "next/font/google";

const montserrat = Montserrat({ subsets: ["latin"], weight: ["400"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body className={montserrat.className}>
        <header>
          <Navbar />
        </header>
        <main className="bg-BG-1">{children}</main>
        <footer>
          <Footer />
        </footer>
      </body>
    </html>
  );
}
